# Generated by Django 5.2.7 on 2025-10-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_des', models.TextField(max_length=1000)),
                ('recipe_image', models.ImageField(upload_to='recipies/')),
            ],
        ),
    ]
