# Generated by Django 5.2.7 on 2025-10-22 19:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_des',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
